name: Development Github Actions

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - run: mvn --batch-mode clean test-compile
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jSEPA-compile
          retention-days: 1
          path: "./target/*"

  verify:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - run: mvn --batch-mode verify
      - uses: actions/download-artifact@v4
        with:
          name: jSEPA-compile
          path: ./target/
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jSEPA-target
          path: "./target/*"