name: Development Github Actions

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  compile:
    if: github.event_name == 'push' && !contains(github.event.pull_request.base.ref, 'main')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Compile jSEPA
        run: mvn --batch-mode clean test-compile
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jSEPA-compile
          retention-days: 1
          path: "./target/*"

  verify:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          name: jSEPA-compile
          path: ./target/
      - name: Verify jSEPA
        run: mvn --batch-mode verify
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jSEPA-verify
          path: "./target/*"