name: Test the signing of artefacts

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          gpg --list-keys --keyid-format LONG
      - name: Package jSEPA
        run: |
          mvn \
            --batch-mode \
            -Psign \
            clean verify
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jSEPA-compile
          retention-days: 1
          path: "./target/*"